---
collections:
  - name: community.crypto
    source: https://github.com/ansible-collections/community.crypto
    type: git
  - name: community.hashi_vault
    source: https://github.com/ansible-collections/community.hashi_vault
    type: git
  - name: https://opendev.org/openstack/openstack-ansible-plugins
    type: git
    version: master
