---
collections:
  - name: community.crypto
    version: 2.0.2
    source: https://galaxy.ansible.com
  - name: community.hashi_vault
    version: 6.2.0
  - name: https://opendev.org/openstack/openstack-ansible-plugins
    type: git
    version: master
