---
- name: Prepare
  hosts: all
  tasks:
    - name: Create test group
      ansible.builtin.group:
        name: test

    - name: Create test user
      ansible.builtin.user:
        name: test
        group: test

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when:
        - ansible_facts['os_family'] | lower == 'debian'

    - name: Install packages
      ansible.builtin.package:
        name: "{{ molecule_packages[ansible_facts['os_family'] | lower] }}"
